// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOozwg3iADBptK5sfzl-93Jl40aYhfn8',
    appId: '1:1045749984100:web:c3d56aa099f1ad7226e871',
    messagingSenderId: '1045749984100',
    projectId: 'projet-app-a6b92',
    authDomain: 'projet-app-a6b92.firebaseapp.com',
    storageBucket: 'projet-app-a6b92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jKUdyOEpPqSmnZE2ibkwBSCaiBohG2Y',
    appId: '1:1045749984100:android:d184a2da64b5280926e871',
    messagingSenderId: '1045749984100',
    projectId: 'projet-app-a6b92',
    storageBucket: 'projet-app-a6b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nJrB9P2wNSAlxW4feLEvgF_b_9gJ5_0',
    appId: '1:1045749984100:ios:161ffdc62bbb22ca26e871',
    messagingSenderId: '1045749984100',
    projectId: 'projet-app-a6b92',
    storageBucket: 'projet-app-a6b92.appspot.com',
    iosClientId: '1045749984100-0sum78sh5uf527sfgp3lds19t2rb0gai.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5nJrB9P2wNSAlxW4feLEvgF_b_9gJ5_0',
    appId: '1:1045749984100:ios:f044769b4fb92e0026e871',
    messagingSenderId: '1045749984100',
    projectId: 'projet-app-a6b92',
    storageBucket: 'projet-app-a6b92.appspot.com',
    iosClientId: '1045749984100-nb12g7aqjcv385r1m0ko0g8t9vkpaalb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetApp.RunnerTests',
  );
}
